name: Build API CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  
jobs:
  api-build:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
       
      - name: Install Dependencies 
        run: dotnet restore
        working-directory: ECommerce.Api/
       
      - name: Build
        run: dotnet build --configuration Release -warnaserror --no-restore
        working-directory: ECommerce.Api/
